apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node-github-tekton-060625
  janus-idp.io/tekton: node-github-tekton-060625
  backstage.io/kubernetes-id: node-github-tekton-060625
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: node-github-tekton-060625
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
