apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: node-github-tekton-060625
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-github-tekton-060625 
  name: node-github-tekton-060625
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: node-github-tekton-060625 
